#!/bin/bash
set -e

cargo build --release --features generate --locked --target-dir target
scripts/mkmo locale/
strip target/release/pinky

tar --zstd -cf pinky.tar.zst man completions pinky.conf locale -C target/release pinky

