#!/bin/bash
set -e

cargo build --release --features generate --locked --target-dir target
scripts/mkmo locale/
strip target/release/tsuki

tar --zstd -cf tsuki.tar.zst man completions tsuki.conf locale -C target/release tsuki

