#!/bin/sh
set -e

xtr \
	-d tsuki \
	--msgid-bugs-address https://github.com/ElvaraOS-Team/tsuki \
	--package-name=tsuki\
	--package-version="$(awk -F '=' '/^version/ {print $2}' Cargo.toml | sed 's/\"//g')" \
	-k printtr -k tr \
	-o=po/tsuki.pot \
	src/lib.rs
